### ISSUE TITLE
app problems don't render correctly in slack

### ISSUE THREAD

**Issue by kurtismgit** [ibm-cloud-solutions/hubot-ibmcloud-alerts#10]
I enable app event monitoring and forced an application to crash.  Then I asked the bot to 'app show me problems today' and the bot responded with this text:

The 1 most problematic applications today are … <ol>
<li>The <code>kbot-test-app-svt</code> application crashed <code>1</code> time.</li>
</ol>

Seems to be markdown tags shown in slack.  I'm not certain if this problem is with this project or potentially and issue with `hubot-ibmcloud-formatter`

**Comment by kurtismgit** [comment]
<img width="527" alt="screen shot 2016-08-11 at 1 35 52 pm" src="https://cloud.githubusercontent.com/assets/7569099/17598465/b57cbf12-5fc8-11e6-8d17-f484dd166ac6.png">

**Comment by clanzen** [comment]
I'm closing this out based on opening a new issue where the fix needs to be made, in the hubot-ibmcloud-formatter as you were guessing.
https://github.com/ibm-cloud-solutions/hubot-ibmcloud-formatter/issues/8
